### ISSUE TITLE
build error for python bindings with opencv_contrib modules

### ISSUE THREAD

**Issue by heinerb** [Kitware/fletch#101]
The version of OpenCV that is pulled down was throwing the following error when compiling the extra modules.

fatal error: hdf5.h: No such file or directory

Small modification of the modules/python/common.cmake solves the issue.

find_package(HDF5)
include_directories(${HDF5_INCLUDE_DIRS})

Can this be added to the OpenCV 3.1 patches in the fletch cmakes?

https://github.com/Kitware/fletch/blob/master/Patches/OpenCV3/Patch.cmake

**Comment by mattbrown11** [comment]
FWIW, I had the same issue.

**Comment by dstoup** [comment]
We've since upgraded to version 3.4.0. I believe this issue is resolved.
