### ISSUE TITLE
allow turning VTK_DEBUG_LEAKS off for release builds

### ISSUE THREAD

**Issue by mleotta** [Kitware/fletch#15]
currently VTK_DEBUG_LEAKS in VTK is set on by default.  This is useful for debug builds, but can be annoying when trying to make release binaries (especially on Windows). If not all leaks have been addressed it will pop up a bunch of error dialogs when closing an application.  Is there a way we can make this OFF by default for Release builds of VTK and ON for Debug builds?  Or maybe just propagate this option up to the Fletch CMake options?

**Comment by dstoup** [comment]
Address in https://github.com/Kitware/fletch/pull/292

**Comment by dstoup** [comment]
I made VTK_DEBUG_LEAK an advance option which defaults to OFF
