### ISSUE TITLE
fletch cmake minimum version < than cmake minimum version of some packages

### ISSUE THREAD

**Issue by d-hoke** [Kitware/fletch#159]
Fletch readme and CMakeLists.txt indicates minimum cmake version of 2.8.12.

Some of the packages built by fletch currently appear to need minimum of cmake 3.1 for some host environments.

(grep -r --include="CMakeLists.txt" cmake_minimum_required . from top of fletch binary dir.)

**Comment by dstoup** [comment]
Fixed in https://github.com/Kitware/fletch/pull/291
