### ISSUE TITLE
Qt in Fletch Doesn't Build with Latest Compilers

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/fletch#161]
e.g. on Fedora 24, the default compiler (gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)) is too new and multiple error messages incur because of this.

**Comment by dstoup** [comment]
Is this issue fixed? I would like to close outdated issues. I believe I fixed this issue several months ago.

**Comment by dstoup** [comment]
Bump. Please verify. I will close otherwise. We have Qt 4 building nightly on gcc version 7.3.1 20180303

**Comment by dstoup** [comment]
Fixed and closing.
