### ISSUE TITLE
A few opencv issues after 2.4.11 to 2.4.13 and 3.1.1 upgrade

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/fletch#205]
I'm not sure that the default opencv version in fletch should be 3.1, does caffe play nicely with it?

Building opencv on windows with 2.4.13 and libtiff / libjpeg turned off has lots of linker issues now

**Comment by mattdawkins** [comment]
@Erotemic @dstoup

**Comment by Erotemic** [comment]
That's weird. I didn't update opencv 2.4.11 to 2.4.13. It was always 2.4.13, but the string in the combo box was just incorrectly set to 2.4.11. I just fixed the text. 

Can you verify that this doesn't happen if you checkout a previous commit?

**Comment by mleotta** [comment]
I strongly feel that the default OpenCV in Fletch should be > 3.0.  In addition to there being new features in 3.X that we want to take advantage of, there is a least one long-standing issue (recently reported as Kitware/kwiver#269) with the OpenCV/Vital image wrapper that cannot be fixed using OpenCV 2.4.X  A fix should be possible with 3.X.

I'd be surprised if Caffe doesn't support 3.X (or if someone hasn't patched it to support 3.X on a branch somewhere).  I'd rather patch Caffe to work with OpenCV 3 than roll Fletch back to OpenCV 2.4.  We could also try to disable OpenCV in Caffe if we are not using it there.

**Comment by hughed2** [comment]
Is this one of the errors you saw?

/build/src/OpenCV_contrib/modules/sfm/src/libmv_capi.h:106:3: error: 'SetCommandLineOption' is not a member of 'google'
   google::SetCommandLineOption("v", val);
   ^

**Comment by dstoup** [comment]
I am assuming these issues are resolved since we are using OpenCV 3.4. If it reoccurs, feel free to reopen this issue.
