### ISSUE TITLE
OpenCV does not use image libraries from Fletch

### ISSUE THREAD

**Issue by mleotta** [Kitware/fletch#23]
When building Fletch on Linux with all packages turned on, OpenCV does not use the Fletch builds of libtiff, libjpeg, libpng, and libz if system packages are available.  It uses the system packages.  The build completes successfully, but building something against Fletch reports errors due to multiple different versions of these libraries.

**Comment by dstoup** [comment]
I believe these packages are now correctly passes to OpenCV. Can we close this issue?

**Comment by mleotta** [comment]
Yes, I think it works now
