### ISSUE TITLE
Qt build error on MacOS/clang

### ISSUE THREAD

**Issue by chetnieter** [Kitware/fletch#269]
I get the following build error when building Qt via fletch on my Mac.

messagemodel.cpp:186:61: error: ordered comparison between pointer and zero ('MessageItem *' and 'int')
                if (c->findMessage(m->text(), m->comment()) >= 0)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~

**Comment by mleotta** [comment]
Can you provide details on your OS and compiler version?  I have not seen this on my Macs.

**Comment by chetnieter** [comment]
Sierra 10.12.6

Apple LLVM version 9.0.0 (clang-900.0.38)

**Comment by mleotta** [comment]
I'm on Sierra, but with LLVM 8.0.0.  I've been holding off on upgrading XCode due to potential issues with with CUDA (I have an older MBP with a NVidia card).  My dashboard Mac is even older.  So this is probably due to a change in clang.

**Comment by Cookt2** [comment]
#270 addressed this issue, closing.
