### ISSUE TITLE
Darknet build errors on MacOS/clang

### ISSUE THREAD

**Issue by chetnieter** [Kitware/fletch#271]
I get the following errors when building Darknet via fletch on my Mac. A little googling seems to imply that the 'clock_gettime' method used to be missing on MacOS but apparently it has recently been added. I am running Sierra 10.12.6 with Apple LLVM version 9.0.0 (clang-900.0.38).

[  1%] Building C object src/CMakeFiles/darknet_lib.dir/utils.c.o
/Users/chet.nieter/projects/ComputerVision/fletch/build/rel/build/src/Darknet/src/utils.c:89:9: warning: 'CLOCK_REALTIME' macro
      redefined [-Wmacro-redefined]
#define CLOCK_REALTIME 0
        ^
/usr/include/time.h:154:9: note: previous definition is here
#define CLOCK_REALTIME _CLOCK_REALTIME
        ^
/Users/chet.nieter/projects/ComputerVision/fletch/build/rel/build/src/Darknet/src/utils.c:91:5: fatal error: conflicting types for
      'clock_gettime'
int clock_gettime(int X, struct timespec *tv)
    ^
/usr/include/time.h:177:5: note: previous declaration is here
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);
    ^
1 warning and 1 error generated.

**Comment by Cookt2** [comment]
I believe this error is no longer relevant. I haven't had any troubles building Darknet via Fletch. Mac dashboards pass with Apple Clang 9 and OS 10.13. Closing issue.
