### ISSUE TITLE
OpenCV Needs to be patched to support CUDA 9

### ISSUE THREAD

**Issue by mleotta** [Kitware/fletch#280]
OpenCV 3.1 does not build against CUDA 9.  This doesn't appear to be resolved in OpenCV 3.3 yet either, but I haven't tested it.  The error message is as follows:

    CUSTOMBUILD : CMake error : The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    CUDA_nppi_LIBRARY (ADVANCED)

I observed this on Windows 10, but this [stackoverflow post](https://stackoverflow.com/questions/46584000/cmake-error-variables-are-set-to-notfound) indicates the same problem occurs with Ubuntu and with OpenCV 3.3.  It also offers a recommendation on how to patch it.

**Comment by dstoup** [comment]
Addressed in PR 288
