### ISSUE TITLE
Boost 1.55  error on Fedora 23

### ISSUE THREAD

**Issue by Purg** [Kitware/fletch#30]
Apparently there is a known issues with boost 1.55 that is fixed in newer versions:
- https://svn.boost.org/trac/boost/ticket/9534
- https://svn.boost.org/trac/boost/ticket/9805

Not sure if we care, want to work around this on the systems that it affects or upgrade to a newer version of boost.

**Comment by dstoup** [comment]
We are building on this platform as well as providing a newer version. Closing.
