### ISSUE TITLE
Caffe not building on windows with CUDA enabled

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/fletch#330]
1>CUSTOMBUILD : CMake error : Parse error in cache file D:/Dev/viame/build-vs15/build/src/fletch-build/build/src/Caffe-build/CMakeCache.txt on line 890. Offending entry: detect_cuda_archs.cu [D:\Dev\viame\build-vs15\build\src\fletch-build\Caffe.vcxproj]
1>CUSTOMBUILD : CMake error : Parse error in cache file D:/Dev/viame/build-vs15/build/src/fletch-build/build/src/Caffe-build/CMakeCache.txt on line 891. Offending entry: Creating library a.lib and object a.exp [D:\Dev\viame\build-vs15\build\src\fletch-build\Caffe.vcxproj]
1>CUSTOMBUILD : CMake error : Parse error in cache file D:/Dev/viame/build-vs15/build/src/fletch-build/build/src/Caffe-build/CMakeCache.txt on line 892. Offending entry: 3.0 [D:\Dev\viame\build-vs15\build\src\fletch-build\Caffe.vcxproj]
1>

CMakeCache contents:

line 886 //ADVANCED property for variable: CUDA_cusparse_LIBRARY
CUDA_cusparse_LIBRARY-ADVANCED:INTERNAL=1
//Returned GPU architetures from caffe_detect_gpus tool
CUDA_gpu_detect_output:INTERNAL=nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
//Location of make2cmake.cmake
CUDA_make2cmake:INTERNAL=C:/Program Files/CMake/share/cmake-3.8/Modules/FindCUDA/make2cmake.cmake
//ADVANCED property for variable: CUDA_nppc_LIBRARY
CUDA_nppc_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CUDA_nppi_LIBRARY
CUDA_nppi_LIBRARY-ADVANCED:INTERNAL=1

**Comment by mattdawkins** [comment]
This only happens when CUDA is turned on

**Comment by dstoup** [comment]
What CUDA version are you using?

**Comment by mattdawkins** [comment]
v8.0

**Comment by mattdawkins** [comment]
Previously this worked FYI (~4 months ago at least). Trying a partial reversion

**Comment by daniel-riehm** [comment]
Closing, as Caffe was removed in #710
