### ISSUE TITLE
OpenJPEG missing dependency on PNG

### ISSUE THREAD

**Issue by mleotta** [Kitware/fletch#346]
OpenJPEG depends on libpng, but Fletch does not express this dependency.  When running parallel builds Fletch will sometimes build OpenJPEG before libpng and then OpenJPEG may find a system version of libpng which is incompatible.

**Comment by dstoup** [comment]
Apparently I fixed this about a month after the issue was opened. I've confirmed that PNG does properly get added as an openjpeg dep.
