### ISSUE TITLE
Latest Eigen version build errors on Mac

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/fletch#347]
On master:

CMake Warning at cmake/FindBLAS.cmake:1371 (message):
   BLA_VENDOR has been set to All but blas libraries could not be found or
   check of symbols failed.

   Please indicate where to find blas libraries.  You have three options:

   - Option 1: Provide the installation directory of BLAS library with cmake
   option: -DBLAS_DIR=your/path/to/blas

   - Option 2: Provide the directory where to find BLAS libraries with cmake
   option: -DBLAS_LIBDIR=your/path/to/blas/libs

   - Option 3: Update your environment variable (Linux: LD_LIBRARY_PATH,
   Windows: LIB, Mac: DYLD_LIBRARY_PATH)

   To follow libraries detection more precisely you can activate a verbose
   mode with -DBLAS_VERBOSE=ON at cmake configure.

   You could also specify a BLAS vendor to look for by setting
   -DBLA_VENDOR=blas_vendor_name.

   List of possible BLAS vendor: Goto, ATLAS PhiPACK, CXML, DXML, SunPerf,
   SCSL, SGIMATH, IBMESSL, Intel10_32 (intel mkl v10 32 bit),Intel10_64lp
   (intel mkl v10 64 bit, lp thread model, lp64 model), Intel10_64lp_seq
   (intel mkl v10 64 bit, sequential code, lp64 model),Intel( older versions
   of mkl 32 and 64 bit), ACML, ACML_MP, ACML_GPU, Apple, NAS, Generic
 Call Stack (most recent call first):
   cmake/FindLAPACK.cmake:138 (find_package)
   test/CMakeLists.txt:30 (find_package)

 CMake Error: CMAKE_Fortran_COMPILER not set, after EnableLanguage

 CMake Error: Internal CMake error, TryCompile configure of cmake failed

 CUDA_TOOLKIT_ROOT_DIR not found or specified

 CMake Warning (dev) in bench/spbench/CMakeLists.txt:
   A logical block opening on the line

     /Users/matt.dawkins/Dev/viame/build/build/src/fletch-build/build/src/Eigen/bench/spbench/CMakeLists.txt:51 (if)

   closes on the line

     /Users/matt.dawkins/Dev/viame/build/build/src/fletch-build/build/src/Eigen/bench/spbench/CMakeLists.txt:63 (endif)

**Comment by mattdawkins** [comment]
Previous version was fine

**Comment by dstoup** [comment]
Fixed in #358

**Comment by dstoup** [comment]
Assuming this is resolved, closing.
