### ISSUE TITLE
Fletch is not exporting fletch_ENABLED_GDAL

### ISSUE THREAD

**Issue by mleotta** [Kitware/fletch#381]
@chetnieter @dstoup , the following line is missing

    set(fletch_ENABLED_GDAL TRUE)

It needs to go roughly here:
https://github.com/Kitware/fletch/blob/ea5e544dd3a94f42e1da712ccf0c7eacf876c436/CMake/External_GDAL.cmake#L200

**Comment by dstoup** [comment]
Fixed in PR #382

**Comment by dstoup** [comment]
Jenkins test this please
