### ISSUE TITLE
Qt compile error

### ISSUE THREAD

**Issue by tpinky** [Kitware/fletch#47]
On Debian 8.4.0 following error occures:

[  6%] Performing configure step for 'Qt'

This is the Qt for Linux/X11 Open Source Edition.

You are licensed to use this software under the terms of
the Lesser GNU General Public License (LGPL) versions 2.1.
You are also licensed to use this software under the terms of
the GNU General Public License (GPL) versions 3.

You have already accepted the terms of the  license.

Creating qmake. Please wait...
Basic XLib functionality test failed!
 You might need to modify the include and library search paths by editing
 QMAKE_INCDIR_X11 and QMAKE_LIBDIR_X11 in /home/tpinkowski/fletch/build/src/Qt/mkspecs/linux-g++-64.
CMakeFiles/Qt.dir/build.make:107: recipe for target 'build/src/Qt-stamp/Qt-configure' failed

**Comment by dstoup** [comment]
That means you are missing some dev packages for X11. At a minimum, try to install libXt-dev. I don't use Debian, so I don't know if the capitalization is exactly right. Do a package search to determine the correct name. It's possible you are missing a few other X11 related dev packages, but libxt usually brings them in as deps.

If you want Qt-GUI, make sure you have dev packages for glu and glut as well. On Fedora I typically install free-glut-devel and mesa-libGLU-devel

**Comment by tpinky** [comment]
libx11-dev, libXrender-dev, libXext-dev
solved it for me. Somehow.
