### ISSUE TITLE
Qt 5.11.2 no longer available

### ISSUE THREAD

**Issue by bradh** [Kitware/fletch#537]
During a telesculptor superbuild, I hit problems with the Qt dependency. It appears that `http://download.qt-project.org/official_releases/qt/` no longer provides 5.11.

The options at this point (late June 2019) are 5.12.4 and 5.13.0. I'm thinking stable on this one.

**Comment by bradh** [comment]
Resolved by #538

**Comment by Cookt2** [comment]
Closing this issue, as it appears to have been resolved.
