### ISSUE TITLE
Python Option is Hidden

### ISSUE THREAD

**Issue by mleotta** [Kitware/fletch#55]
The option to enable Python in Fletch is hidden as an advanced option.  It does not turn on when enabling all packages.  KWIVER has a top-level CMake option to enable Python and Python is required to build Sprokit in KWIVER.  Both of these options in KWIVER will fail when built against a Fletch that does not have Python enabled.  It seems we should also promote Python to a top-level (non-hidden) option in Fletch, and possible even turn it on when selecting "build all packages".

**Comment by dstoup** [comment]
I've already started looking into this issue. I think, at minimum the option should not be advanced, and most likely it should default to ON provided the correct python environment is available. Thoughts?

**Comment by mattdawkins** [comment]
https://github.com/Kitware/fletch/pull/63
