### ISSUE TITLE
enabling ffnvcodec causes build problems in Ubuntu

### ISSUE THREAD

**Issue by borovik135** [Kitware/fletch#718]
Setting fletch_ENABLE_ffnvcodec=ON causes build issues in Ubuntu, i.e.
$ make 
[  2%] Performing install step for 'ffnvcodec'
install: cannot change permissions of ‘/usr/local/include/ffnvcodec’: No such file or directory
make[3]: *** [Makefile:14: install] Error 1
make[2]: *** [CMakeFiles/ffnvcodec.dir/build.make:74: build/src/ffnvcodec-stamp/ffnvcodec-install] Error 2
make[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/ffnvcodec.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Machine details (please complete the following information):**
- OS: Ubuntu 20.04 LTS
- CMake version 3.16.3
- Compiler c++ (Ubuntu 8.4.0-3ubuntu2) 8.4.0
- Fletch master bb14e83

**Comment by daniel-riehm** [comment]
Fixed in #719
