### ISSUE TITLE
Clarify what "Building Fletch" means

### ISSUE THREAD

**Issue by dabrahams** [Kitware/fletch#750]
[Building Fletch](https://github.com/Kitware/fletch?tab=readme-ov-file#building-fletch) is a section in the README, but since it also says Fletch is “a pure CMake project” it's unclear what it might mean to build fletch, and the README is confusing.  I can, if I stretch my brain a bit, imagine that Fletch contains some generated CMake files, perhaps?  What Fletch actually _is_ would be a lot clearer if you'd spell that info out.
Thanks

**Comment by aronhelser** [comment]
I think the "Motivation" section spells this out pretty clearly. Maybe there is a better organization that would be clearer?

**Comment by dabrahams** [comment]
No, it doesn't explain what "building fletch" means, unless in this context "building fletch" means _building what "fletch builds"_ (according to the same section): OpenCV, VXL, VTK, etc.

I got the impression from the Motivation section that Fletch is a generalized package manager that just happens to be used, in its default configuration, for a very specific purpose, but maybe the truth is that it is just a project to encode the build instructions for a bunch of Kwiver dependencies?

**Comment by Erotemic** [comment]
Would it help to add a blurb like:

Building Fletch results in a set of inter-compatable shared libraries suitable for use in downstream applications - with the primary consumer being [KWIVER](https://github.com/Kitware/kwiver). Using the CMake configuration, the user specifies which libraries to build, and Fletch handles ensuring the chosen set is compatible.

**Comment by dabrahams** [comment]
Yes that would clear it up
