### ISSUE TITLE
Missing header in Boost Python install

### ISSUE THREAD

**Issue by mleotta** [Kitware/fletch#82]
When building Boost with Python enabled, the following file is found in the source tree but not installed:

    boost/python/raw_function.hpp

This becomes a problem when also building Caffe, which uses this file.  The resulting error is

    /home/vagrant/Software/fletch/build/build/src/Caffe/python/caffe/_caffe.cpp:8:41: fatal error: boost/python/raw_function.hpp: No such file or directory
    #include <boost/python/raw_function.hpp>

I have encountered this error on Centos 7.  This issue was also listed as a known issue for VIAME: https://github.com/Kitware/VIAME/blob/master/doc/install_guide.rst#id10

**Comment by mattdawkins** [comment]
I fixed it in VIAME by writing a quick cmake function which copies it over.
forgot if it was on the fletch side or viame (there is a fletch
viame/master I should probably reconcile with master)

**Comment by mleotta** [comment]
Yes, fixes like this need to make their way back into master.

I'm not sure why this is broken.  It looks the CMake install command does a batch copy of the "boost" directory from source to the "include/boost" install directory.  It looks like several files are not installed.  I'm not sure why some would be copied and not others.

**Comment by mleotta** [comment]
Nevermind, it's in the source tree, but not copied by Boost into the build tree headers.  The build tree headers are then copied into the install tree.

**Comment by dstoup** [comment]
I'm assuming this issue is fixed. Can I close?

**Comment by dstoup** [comment]
Looks like the header is installed now.

**Comment by zackgalbreath** [comment]
I realize this issue is closed, but this type of error should be less frequent now that #421 is merged.
