### ISSUE TITLE
Possible Updates in Readme

### ISSUE THREAD

**Issue by heinerb** [Kitware/fletch#91]
I recently compiled the Kitware / fletch project and found the following dependency items which may be worth placing in README file. 

1. The version of OpenCV 3.1.0 pulled from the latest fletch repo does not support CUDA 8.0 Toolkit. later versions of OpenCV resolve issue. Looks like CUDA 7.5 does meet needs. 

2. Some of the compile items for python required unicode = ucs4 (Enthought/Canopy issues since it used ucs2)

**Comment by Cookt2** [comment]
Current Fletch provides OpenCV 3.4. This version supports all the way up to CUDA 9.0. I'm closing this issue as it appears to be deprecated. Thanks!
